export class Marketplace {
	mkcoMkplUuid : string;
    mkcoMkplName : string;
	mkcoMkplCode : string;
	mkcoProdUuid : string;
	mkcoProdName : string;
	mkcoStartActiveDate : string;
	mkcoInactiveDate : string;
	mkcoCompanyCode : string;
	mkcoScoreCard : string;
	mkcoFeeAmountType : string;
	mkcoFeeAmountTypeDesc : string;
	mkcoFeeAmount : number;
	mkcoFeeMinAmount : number;
	mkcoFeeMaxAmount : number;
	mkcoDisburseInfoUrl : string;
	mkcoOtherInfoUrl01 : string;
	mkcoOtherInfoUrl02 : string;
	mkcoOtherInfoUrl03 : string;
	mkcoOtherInfoUrl04 : string;
	mkcoOtherInfoUrl05 : string;
	mkcoAuthUrl : string;
	mkcoAuthCliectId : string;
	mkcoAuthKey : string;
	mkcoEncryptedFlag : boolean;
	mkcoEncryptionMethod : string;
	mkcoEncryptionKey : string;
	mkcoRef1Desc : string;
	mkcoRef2Desc : string;
	mkcoRef3Desc : string;
	mkcoRef4Desc : string;
	mkcoRef5Desc : string
}